imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@AppBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true


# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        server_version: 5.7
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

hwi_oauth:
    connect:
        account_connector: hwi_oauth.user.provider.entity
    firewall_names:        ['secured_area']
    fosub:
        username_iterations: 30
        properties:
            facebook:    facebookId
    resource_owners:
        facebook:
            type:          facebook
            client_id:     2251951438363364
            client_secret: d60fcef11d32f41782018cb53002c2b0
            scope:         public_profile,email
            options:
                csrf:      true
                display:   popup     #dialog is optimized for popup window
                auth_type: rerequest # Re-asking for Declined Permissions
                appsecret_proof: true

fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: oauth_authorize
    user_class: AppBundle\Entity\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"
#    service:
#        user_manager: app.user_manager
    registration:
        confirmation:
            enabled: true
        form:
            type: AppBundle\Form\RegistrationType

fos_oauth_server:
    db_driver: orm       # Drivers available: orm, mongodb, or propel
    client_class:        AppBundle\Entity\Client
    access_token_class:  AppBundle\Entity\AccessToken
    refresh_token_class: AppBundle\Entity\RefreshToken
    auth_code_class:     AppBundle\Entity\AuthCode

    service:
        user_provider: fos_user.user_provider.username

jms_serializer:
    metadata:
        directories:
            FOSUB:
                namespace_prefix: "FOS\\UserBundle"
                path: "%kernel.root_dir%/Resources/FOSUserBundle/serializer"

#http://symfony.com/doc/master/bundles/FOSRestBundle/configuration-reference.html
fos_rest:
    #http://symfony.com/doc/master/bundles/FOSRestBundle/body_listener.html
    body_listener:
        default_format: json

    #http://symfony.com/doc/master/bundles/FOSRestBundle/view_response_listener.html
    view:
        view_response_listener: force
        formats:
            json: true

    #http://symfony.com/doc/master/bundles/FOSRestBundle/format_listener.html
    format_listener:
        rules:
            - { path: '^/oauth/v2/auth', fallback_format: html }
            - { path: '^/oauth/v2/user', fallback_format: html }
            - { path: '^/login', fallback_format: html }
            - { path: '^/connect', fallback_format: html }
            - { path: '^/', priorities: ['json'], fallback_format: json , prefer_extension: true }

    #http://symfony.com/doc/current/bundles/FOSRestBundle/5-automatic-route-generation_single-restful-controller.html#optional-format-in-route
    routing_loader:
        include_format: false
    disable_csrf_role: IS_AUTHENTICATED_FULLY
