hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

facebook_login:
    path: /login/check-facebook
#    defaults:  { _controller: AppBundle:Users:login, _method: GET }
#    requirements:
#        service: facebook

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /oauth/v2/user

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

fos_user_security_login:
    path:      /oauth/v2/auth_login
    defaults:  { _controller: FOSUserBundle:Security:login, _method: POST }

fos_user_security_logout:
    path:      /oauth/v2/auth_logout
    defaults:  { _controller: FOSUserBundle:Security:logout, _method: POST }

fos_user_security_check:
    path:      /oauth/v2/auth_check
    defaults:  { _controller: FOSUserBundle:Security:check, _method: POST }

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    type: rest
    prefix: /

not_found:
    path:  /{path}
    defaults: { _controller: AppBundle:NotFount:index  }
    requirements:
        path: ".+"
