parameters:
    jms_serializer.form_error_handler.class: AppBundle\Serializer\Normalizer\FormErrorHandler
#    jms_serializer.naming_strategy:
#        class: JMS\Serializer\Naming\IdenticalPropertyNamingStrategy

services:
#    app.base_user_manager:
#        class: FOS\UserBundle\Model\UserManager
#        abstract: true
#        public: false
#        arguments: ["@fos_user.util.password_updater", "@fos_user.util.canonical_fields_updater"]
#
#    app.user_manager:
#        class: AppBundle\Model\Manager\UserManager
#        parent: app.base_user_manager

    app.user_manager:
        class: AppBundle\Model\Manager\UserManager
        arguments: ["@fos_user.util.password_updater", "@fos_user.util.canonical_fields_updater", "@fos_user.object_manager", 'AppBundle\Entity\User']

#    app.user_type:
#        class: AppBundle\Form\UserType
