AppBundle\Entity\User:
    type: entity
    repositoryClass: AppBundle\Repository\UserRepository
    lifecycleCallbacks:
        prePersist: [setCreatedAt, setUpdatedAt]
        preUpdate: [setUpdatedAt]
    id:
        id:
            id: true
            type: integer
            generator:
                strategy: AUTO
    fields:
        firstName:
            type: string
            length: 255
        lastName:
            type: string
            length: 255
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
